"""initial schema

Revision ID: 1f76a204ea5c
Revises: 
Create Date: 2026-03-18 23:35:29.109930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1f76a204ea5c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_cache',
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('data_type', sa.Enum('race_list', 'race_detail', 'startlist', 'stages', 'stage_winners', name='scrape_data_type'), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('etag', sa.String(length=256), nullable=True),
    sa.Column('is_immutable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_report',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reporter_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diary_entry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('race_url', sa.Text(), nullable=False),
    sa.Column('race_name', sa.String(length=512), nullable=False),
    sa.Column('race_year', sa.Integer(), nullable=False),
    sa.Column('race_base_slug', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('key_moment', sa.Text(), nullable=True),
    sa.Column('protagonist', sa.String(length=256), nullable=True),
    sa.Column('dominant_emotion', sa.String(length=128), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('share_token', sa.UUID(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_table('review_like',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', name='uq_review_like_user_target')
    )
    op.create_table('mention',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diary_entry_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('rider', 'location', 'team', name='entity_type_enum'), nullable=False),
    sa.Column('entity_name', sa.String(length=512), nullable=False),
    sa.Column('entity_slug', sa.Text(), nullable=False),
    sa.Column('entity_metadata', sqlite.JSON(), nullable=True),
    sa.Column('mention_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detection_method', sa.Enum('fuzzy', 'spacy', 'llm', 'manual', name='detection_method_enum'), nullable=False),
    sa.Column('confirmed_by_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['diary_entry_id'], ['diary_entry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_comment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('diary_entry_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['diary_entry_id'], ['diary_entry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['review_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_comment')
    op.drop_table('mention')
    op.drop_table('review_like')
    op.drop_table('diary_entry')
    op.drop_table('community_report')
    op.drop_table('user_profile')
    op.drop_table('scrape_cache')
    # ### end Alembic commands ###
